
import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Index() {
  let router = useRouter();
  return (
      <div className={styles.container}>
        <Head>
          <title>information</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            这是一个关于id { router.query.postId }页面！
          </h1>
          <button onClick={() => router.push('/center')}>
            Click here to read more
          </button>

        </main>
      </div>
  )
}
