
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import testCss from './test.module.css';

export default function Index() {
  return (
      <div className={styles.container}>
        <Head>
          <title>information</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
           <div className={ testCss.test }>
             这是一个css页！
           </div>
          </h1>

        </main>
      </div>
  )
}
